[platformio]
default_envs = espnow

[env:base]
platform = espressif32@6.9.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200

[env:espnow]
extends = env:base
build_src_filter = 
    +<esp-now/>

[env:vehicle]
extends = env:base
build_src_filter =
    +<common/>
    +<vehicle/>

[env:monitor]
extends = env:base
build_src_filter =
    +<common/>
    +<monitor/>